/*
 * 元素データ (118元素)
 * 各行: [原子番号, 元素記号, 日本語名, 英語名, 周期, 族, ブロック, 分類, 常温での状態]
 *
 * 補足:
 * - ランタノイド(57-71)・アクチノイド(89-103)は表示上の慣例に合わせ族を 3 として扱う
 * - 分類コード: alkali=アルカリ金属 / alkaline=アルカリ土類金属 / transition=遷移金属 /
 *   lanth=ランタノイド / actin=アクチノイド / post=卑金属(ポスト遷移金属) /
 *   metalloid=半金属 / nonmetal=非金属 / halogen=ハロゲン / noble=貴ガス
 * - 状態コード: solid=固体 / liquid=液体 / gas=気体 / unknown=未確認(超重元素)
 * - 113番以降は超重元素のため一部の性質・状態は理論的な予測値
 */
const ELEMENTS = [
  [1, "H", "水素", "Hydrogen", 1, 1, "s", "nonmetal", "gas"],
  [2, "He", "ヘリウム", "Helium", 1, 18, "s", "noble", "gas"],
  [3, "Li", "リチウム", "Lithium", 2, 1, "s", "alkali", "solid"],
  [4, "Be", "ベリリウム", "Beryllium", 2, 2, "s", "alkaline", "solid"],
  [5, "B", "ホウ素", "Boron", 2, 13, "p", "metalloid", "solid"],
  [6, "C", "炭素", "Carbon", 2, 14, "p", "nonmetal", "solid"],
  [7, "N", "窒素", "Nitrogen", 2, 15, "p", "nonmetal", "gas"],
  [8, "O", "酸素", "Oxygen", 2, 16, "p", "nonmetal", "gas"],
  [9, "F", "フッ素", "Fluorine", 2, 17, "p", "halogen", "gas"],
  [10, "Ne", "ネオン", "Neon", 2, 18, "p", "noble", "gas"],
  [11, "Na", "ナトリウム", "Sodium", 3, 1, "s", "alkali", "solid"],
  [12, "Mg", "マグネシウム", "Magnesium", 3, 2, "s", "alkaline", "solid"],
  [13, "Al", "アルミニウム", "Aluminium", 3, 13, "p", "post", "solid"],
  [14, "Si", "ケイ素", "Silicon", 3, 14, "p", "metalloid", "solid"],
  [15, "P", "リン", "Phosphorus", 3, 15, "p", "nonmetal", "solid"],
  [16, "S", "硫黄", "Sulfur", 3, 16, "p", "nonmetal", "solid"],
  [17, "Cl", "塩素", "Chlorine", 3, 17, "p", "halogen", "gas"],
  [18, "Ar", "アルゴン", "Argon", 3, 18, "p", "noble", "gas"],
  [19, "K", "カリウム", "Potassium", 4, 1, "s", "alkali", "solid"],
  [20, "Ca", "カルシウム", "Calcium", 4, 2, "s", "alkaline", "solid"],
  [21, "Sc", "スカンジウム", "Scandium", 4, 3, "d", "transition", "solid"],
  [22, "Ti", "チタン", "Titanium", 4, 4, "d", "transition", "solid"],
  [23, "V", "バナジウム", "Vanadium", 4, 5, "d", "transition", "solid"],
  [24, "Cr", "クロム", "Chromium", 4, 6, "d", "transition", "solid"],
  [25, "Mn", "マンガン", "Manganese", 4, 7, "d", "transition", "solid"],
  [26, "Fe", "鉄", "Iron", 4, 8, "d", "transition", "solid"],
  [27, "Co", "コバルト", "Cobalt", 4, 9, "d", "transition", "solid"],
  [28, "Ni", "ニッケル", "Nickel", 4, 10, "d", "transition", "solid"],
  [29, "Cu", "銅", "Copper", 4, 11, "d", "transition", "solid"],
  [30, "Zn", "亜鉛", "Zinc", 4, 12, "d", "transition", "solid"],
  [31, "Ga", "ガリウム", "Gallium", 4, 13, "p", "post", "solid"],
  [32, "Ge", "ゲルマニウム", "Germanium", 4, 14, "p", "metalloid", "solid"],
  [33, "As", "ヒ素", "Arsenic", 4, 15, "p", "metalloid", "solid"],
  [34, "Se", "セレン", "Selenium", 4, 16, "p", "nonmetal", "solid"],
  [35, "Br", "臭素", "Bromine", 4, 17, "p", "halogen", "liquid"],
  [36, "Kr", "クリプトン", "Krypton", 4, 18, "p", "noble", "gas"],
  [37, "Rb", "ルビジウム", "Rubidium", 5, 1, "s", "alkali", "solid"],
  [38, "Sr", "ストロンチウム", "Strontium", 5, 2, "s", "alkaline", "solid"],
  [39, "Y", "イットリウム", "Yttrium", 5, 3, "d", "transition", "solid"],
  [40, "Zr", "ジルコニウム", "Zirconium", 5, 4, "d", "transition", "solid"],
  [41, "Nb", "ニオブ", "Niobium", 5, 5, "d", "transition", "solid"],
  [42, "Mo", "モリブデン", "Molybdenum", 5, 6, "d", "transition", "solid"],
  [43, "Tc", "テクネチウム", "Technetium", 5, 7, "d", "transition", "solid"],
  [44, "Ru", "ルテニウム", "Ruthenium", 5, 8, "d", "transition", "solid"],
  [45, "Rh", "ロジウム", "Rhodium", 5, 9, "d", "transition", "solid"],
  [46, "Pd", "パラジウム", "Palladium", 5, 10, "d", "transition", "solid"],
  [47, "Ag", "銀", "Silver", 5, 11, "d", "transition", "solid"],
  [48, "Cd", "カドミウム", "Cadmium", 5, 12, "d", "transition", "solid"],
  [49, "In", "インジウム", "Indium", 5, 13, "p", "post", "solid"],
  [50, "Sn", "スズ", "Tin", 5, 14, "p", "post", "solid"],
  [51, "Sb", "アンチモン", "Antimony", 5, 15, "p", "metalloid", "solid"],
  [52, "Te", "テルル", "Tellurium", 5, 16, "p", "metalloid", "solid"],
  [53, "I", "ヨウ素", "Iodine", 5, 17, "p", "halogen", "solid"],
  [54, "Xe", "キセノン", "Xenon", 5, 18, "p", "noble", "gas"],
  [55, "Cs", "セシウム", "Caesium", 6, 1, "s", "alkali", "solid"],
  [56, "Ba", "バリウム", "Barium", 6, 2, "s", "alkaline", "solid"],
  [57, "La", "ランタン", "Lanthanum", 6, 3, "d", "lanth", "solid"],
  [58, "Ce", "セリウム", "Cerium", 6, 3, "f", "lanth", "solid"],
  [59, "Pr", "プラセオジム", "Praseodymium", 6, 3, "f", "lanth", "solid"],
  [60, "Nd", "ネオジム", "Neodymium", 6, 3, "f", "lanth", "solid"],
  [61, "Pm", "プロメチウム", "Promethium", 6, 3, "f", "lanth", "solid"],
  [62, "Sm", "サマリウム", "Samarium", 6, 3, "f", "lanth", "solid"],
  [63, "Eu", "ユウロピウム", "Europium", 6, 3, "f", "lanth", "solid"],
  [64, "Gd", "ガドリニウム", "Gadolinium", 6, 3, "f", "lanth", "solid"],
  [65, "Tb", "テルビウム", "Terbium", 6, 3, "f", "lanth", "solid"],
  [66, "Dy", "ジスプロシウム", "Dysprosium", 6, 3, "f", "lanth", "solid"],
  [67, "Ho", "ホルミウム", "Holmium", 6, 3, "f", "lanth", "solid"],
  [68, "Er", "エルビウム", "Erbium", 6, 3, "f", "lanth", "solid"],
  [69, "Tm", "ツリウム", "Thulium", 6, 3, "f", "lanth", "solid"],
  [70, "Yb", "イッテルビウム", "Ytterbium", 6, 3, "f", "lanth", "solid"],
  [71, "Lu", "ルテチウム", "Lutetium", 6, 3, "d", "lanth", "solid"],
  [72, "Hf", "ハフニウム", "Hafnium", 6, 4, "d", "transition", "solid"],
  [73, "Ta", "タンタル", "Tantalum", 6, 5, "d", "transition", "solid"],
  [74, "W", "タングステン", "Tungsten", 6, 6, "d", "transition", "solid"],
  [75, "Re", "レニウム", "Rhenium", 6, 7, "d", "transition", "solid"],
  [76, "Os", "オスミウム", "Osmium", 6, 8, "d", "transition", "solid"],
  [77, "Ir", "イリジウム", "Iridium", 6, 9, "d", "transition", "solid"],
  [78, "Pt", "白金", "Platinum", 6, 10, "d", "transition", "solid"],
  [79, "Au", "金", "Gold", 6, 11, "d", "transition", "solid"],
  [80, "Hg", "水銀", "Mercury", 6, 12, "d", "transition", "liquid"],
  [81, "Tl", "タリウム", "Thallium", 6, 13, "p", "post", "solid"],
  [82, "Pb", "鉛", "Lead", 6, 14, "p", "post", "solid"],
  [83, "Bi", "ビスマス", "Bismuth", 6, 15, "p", "post", "solid"],
  [84, "Po", "ポロニウム", "Polonium", 6, 16, "p", "metalloid", "solid"],
  [85, "At", "アスタチン", "Astatine", 6, 17, "p", "halogen", "solid"],
  [86, "Rn", "ラドン", "Radon", 6, 18, "p", "noble", "gas"],
  [87, "Fr", "フランシウム", "Francium", 7, 1, "s", "alkali", "solid"],
  [88, "Ra", "ラジウム", "Radium", 7, 2, "s", "alkaline", "solid"],
  [89, "Ac", "アクチニウム", "Actinium", 7, 3, "d", "actin", "solid"],
  [90, "Th", "トリウム", "Thorium", 7, 3, "f", "actin", "solid"],
  [91, "Pa", "プロトアクチニウム", "Protactinium", 7, 3, "f", "actin", "solid"],
  [92, "U", "ウラン", "Uranium", 7, 3, "f", "actin", "solid"],
  [93, "Np", "ネプツニウム", "Neptunium", 7, 3, "f", "actin", "solid"],
  [94, "Pu", "プルトニウム", "Plutonium", 7, 3, "f", "actin", "solid"],
  [95, "Am", "アメリシウム", "Americium", 7, 3, "f", "actin", "solid"],
  [96, "Cm", "キュリウム", "Curium", 7, 3, "f", "actin", "solid"],
  [97, "Bk", "バークリウム", "Berkelium", 7, 3, "f", "actin", "solid"],
  [98, "Cf", "カリホルニウム", "Californium", 7, 3, "f", "actin", "solid"],
  [99, "Es", "アインスタイニウム", "Einsteinium", 7, 3, "f", "actin", "solid"],
  [100, "Fm", "フェルミウム", "Fermium", 7, 3, "f", "actin", "solid"],
  [101, "Md", "メンデレビウム", "Mendelevium", 7, 3, "f", "actin", "solid"],
  [102, "No", "ノーベリウム", "Nobelium", 7, 3, "f", "actin", "solid"],
  [103, "Lr", "ローレンシウム", "Lawrencium", 7, 3, "d", "actin", "solid"],
  [104, "Rf", "ラザホージウム", "Rutherfordium", 7, 4, "d", "transition", "unknown"],
  [105, "Db", "ドブニウム", "Dubnium", 7, 5, "d", "transition", "unknown"],
  [106, "Sg", "シーボーギウム", "Seaborgium", 7, 6, "d", "transition", "unknown"],
  [107, "Bh", "ボーリウム", "Bohrium", 7, 7, "d", "transition", "unknown"],
  [108, "Hs", "ハッシウム", "Hassium", 7, 8, "d", "transition", "unknown"],
  [109, "Mt", "マイトネリウム", "Meitnerium", 7, 9, "d", "transition", "unknown"],
  [110, "Ds", "ダームスタチウム", "Darmstadtium", 7, 10, "d", "transition", "unknown"],
  [111, "Rg", "レントゲニウム", "Roentgenium", 7, 11, "d", "transition", "unknown"],
  [112, "Cn", "コペルニシウム", "Copernicium", 7, 12, "d", "transition", "unknown"],
  [113, "Nh", "ニホニウム", "Nihonium", 7, 13, "p", "post", "unknown"],
  [114, "Fl", "フレロビウム", "Flerovium", 7, 14, "p", "post", "unknown"],
  [115, "Mc", "モスコビウム", "Moscovium", 7, 15, "p", "post", "unknown"],
  [116, "Lv", "リバモリウム", "Livermorium", 7, 16, "p", "post", "unknown"],
  [117, "Ts", "テネシン", "Tennessine", 7, 17, "p", "halogen", "unknown"],
  [118, "Og", "オガネソン", "Oganesson", 7, 18, "p", "noble", "unknown"],
].map(([no, sym, ja, en, period, group, block, cat, state]) => ({
  no,
  sym,
  ja,
  en,
  period,
  group,
  block,
  cat,
  state,
}));

const CATEGORY_LABEL = {
  alkali: "アルカリ金属",
  alkaline: "アルカリ土類金属",
  transition: "遷移金属",
  lanth: "ランタノイド",
  actin: "アクチノイド",
  post: "卑金属",
  metalloid: "半金属",
  nonmetal: "非金属",
  halogen: "ハロゲン",
  noble: "貴ガス",
};

const CATEGORY_COLOR = {
  alkali: "#ef9a6b",
  alkaline: "#f2cf5b",
  transition: "#7fb4e8",
  lanth: "#c993d6",
  actin: "#e88fb0",
  post: "#8fca9a",
  metalloid: "#cddc6a",
  nonmetal: "#6bc4b8",
  halogen: "#f0a08a",
  noble: "#a99be0",
};

const BLOCK_LABEL = { s: "s ブロック", p: "p ブロック", d: "d ブロック", f: "f ブロック" };

const STATE_LABEL = {
  solid: "固体",
  liquid: "液体",
  gas: "気体",
  unknown: "不明",
};
